In [1]:
import random
import numpy as np
import time
import threading

In [2]:
x = np.array([(x*random.randint(0,7)) for x in range(10)])
y = np.array([(x*random.randint(0,7)) for x in range(10)])
z = np.array([(x*0) for x in range(10)])

x.reshape(10,1)
y.reshape(10,1)
z.reshape(10,1)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [3]:
matrix = np.column_stack((x, y, z))

matrix

array([[ 0,  0,  0],
       [ 7,  3,  0],
       [ 8,  8,  0],
       [ 9,  9,  0],
       [ 8, 28,  0],
       [30, 10,  0],
       [ 6, 12,  0],
       [21, 28,  0],
       [32, 32,  0],
       [ 9, 63,  0]])

In [4]:
def brain(t, matrix):
    start = time.time()
    z_res = []
    for i in range(len(matrix)):
        matrix[i,2] = matrix[i,0] + matrix[i,1]
        time.sleep(t)
        print(matrix[i,0], '+', matrix[i,1], '=', matrix[i,2])
        z_res.append(matrix[i,2])
    final = round(time.time() - start, 2)
    
    return z_res, final

## No Threads

In [5]:
t = 1

z, tempo = brain(t, matrix)

print('\nVector resultante z: \n ', z, '\n\n El tiempo de ejecución fue: \n', tempo, 'segundos')

0 + 0 = 0
7 + 3 = 10
8 + 8 = 16
9 + 9 = 18
8 + 28 = 36
30 + 10 = 40
6 + 12 = 18
21 + 28 = 49
32 + 32 = 64
9 + 63 = 72

Vector resultante z: 
  [0, 10, 16, 18, 36, 40, 18, 49, 64, 72] 

 El tiempo de ejecución fue: 
 10.05 segundos


## With Treads

In [6]:
def threads(thread, matrix, t, time_s):
    
    jobs = []
    m = int(len(matrix) / thread)
    
    for i in range(thread):
        print('Thread', i+1)
        jobs.append(threading.Thread(target=brain, args=(t, matrix[i * m: (i + 1) * m,:])))
        jobs[i].start()
    for j in jobs:
        j.join()
        
    tempo = round(time.time() - time_s, 2)
    
    return matrix[:,2], tempo

#### 2 Threaths

In [7]:
tread = 2
t = 1
time_s = time.time()

z, tempo = threads(tread,matrix, t, time_s)
print('\nVector resultante z: \n ', z, '\n\n El tiempo de ejecución fue: \n', tempo, 'segundos')

Thread 1
Thread 2
0 + 0 = 0
30 + 10 = 40
7 + 3 = 10
6 + 12 = 18
8 + 8 = 16
21 + 28 = 49
9 + 9 = 18
32 + 32 = 64
8 + 28 = 36
9 + 63 = 72

Vector resultante z: 
  [ 0 10 16 18 36 40 18 49 64 72] 

 El tiempo de ejecución fue: 
 5.26 segundos


#### 5 Threaths

In [8]:
tread = 5
t = 1
time_s = time.time()

z, tempo = threads(tread,matrix, t, time_s)
print('\nVector resultante z: \n ', z, '\n\n El tiempo de ejecución fue: \n', tempo, 'segundos')

Thread 1
Thread 2
Thread 3
Thread 4
Thread 5
0 + 0 = 0
8 + 8 = 16
8 + 28 = 36
6 + 12 = 18
32 + 32 = 64
7 + 3 = 10
9 + 9 = 18
30 + 10 = 40
21 + 28 = 49
9 + 63 = 72

Vector resultante z: 
  [ 0 10 16 18 36 40 18 49 64 72] 

 El tiempo de ejecución fue: 
 3.03 segundos
